name: terraform-output
description: Retrieve the root-level outputs from a Terraform configuration.
author: Daniel Flook

inputs:
  path:
    description: The path to the Terraform root module directory.
    required: false
    default: "."
  workspace:
    description: Terraform workspace to get outputs from
    required: false
    default: "default"
  backend_config:
    description: List of Terraform backend config values, one per line.
    required: false
    default: ""
  backend_config_file:
    description: |
      List of Terraform backend config files to use, one per line.
      Paths should be relative to the GitHub Actions workspace
    required: false
    default: ""

runs:
  using: docker
  image: docker://ghcr.io/dflook/terraform-github-actions@sha256:16ed5f994e78b4550c2eb5e427d5567ef6fc0d8f5ef9579b12aecadec4f62c96
  entrypoint: /entrypoints/output.sh

branding:
  icon: globe
  color: purple
