name: terraform-output
description: Set the action outputs from terraform configuration outputs
author: Daniel Flook

inputs:
  path:
    description: Path to the terraform configuration
    required: false
    default: .
  workspace:
    description: Name of the terraform workspace
    required: false
    default: default
  backend_config:
    description: List of backend config values to set, one per line
    required: false
    default: ""
  backend_config_file:
    description: Path to a backend config file
    required: false
    default: ""

runs:
  using: docker
  image: docker://danielflook/terraform-github-actions@sha256:17751f4256104e52a4383703b7db8455cdb183cb9f0cb9d7e49e7263e87f51ff
  entrypoint: /entrypoints/output.sh

branding:
  icon: globe
  color: purple
