name: terraform-output
description: Set the action outputs from terraform configuration outputs
author: Daniel Flook

inputs:
  path:
    description: Path to the terraform configuration
    required: false
    default: .
  workspace:
    description: Name of the terraform workspace
    required: false
    default: default
  backend_config:
    description: List of backend configs to set, one per line
    required: false
  backend_config_file:
    description: Path to a backend config file
    required: false

runs:
  using: docker
  image: docker://danielflook/terraform-github-actions@sha256:987dcf3c288a803f37a3fb177d95d9d549d37beff8a5bd23c26390e4bae439e2
  entrypoint: /entrypoints/output.sh

branding:
  icon: globe
  color: purple
