name: terraform-output
description: Set the action outputs from terraform configuration outputs
author: Daniel Flook

inputs:
  path:
    description: Path to the terraform configuration
    required: false
    default: .
  workspace:
    description: Name of the terraform workspace
    required: false
    default: default
  backend_config:
    description: List of backend config values to set, one per line
    required: false
    default: ""
  backend_config_file:
    description: Path to a backend config file
    required: false
    default: ""

runs:
  using: docker
  image: docker://danielflook/terraform-github-actions@sha256:456bfa30fe140388801051677636a73e40368f1b43e13a082eb89e58357db54c
  entrypoint: /entrypoints/output.sh

branding:
  icon: globe
  color: purple
